spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.xhvkkjopjeaeqsgolanr
spring.datasource.password=AldenCabrera12!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

jwt.secret=cinerve-super-secret-key-change-this-in-production
jwt.expiration=86400000

server.port=8080

supabase.url=https://xhvkkjopjeaeqsgolanr.supabase.co
supabase.anon-key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhodmtram9wamVhZXFzZ29sYW5yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI2NTM2MzgsImV4cCI6MjA4ODIyOTYzOH0.-Y7SiQSG7m6AHxVQS3DzV3Lj_JAHIAk6WwEhiS6yZto